In [1]:
import cv2

In [4]:
im_g = cv2.imread("smallgray.png", 0)

In [5]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [8]:
cv2.imwrite("new_small_grey.png", im_g)

True

In [9]:
im_g[0,0]

187

In [10]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [11]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [12]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [13]:
import numpy

In [14]:
ims = numpy.hstack((im_g, im_g))

In [15]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
ims = numpy.hstack((im_g, im_g, im_g))

In [17]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [18]:
ims = numpy.vstack((im_g, im_g, im_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [20]:
lst = numpy.hsplit(ims, 5)
print(lst)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [21]:
lst = numpy.vsplit(ims, 3)
print(lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [22]:
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)